let to = require('../Accounts/address.js').towaddress;
let from = require('../Accounts/address.js').fromaddress;
let password = require('../Accounts/password.js').password;
let CoinAmount = require('../interface/Amount.js').CoinAmount;
let sendAmount = new CoinAmount(200);
let nonce = 310;
let PrivacySend = require('../transactions/privacyTrans.js');
let privacy = new PrivacySend(from.account1,to.fanghua,sendAmount,nonce);
let data = privacy.signFromKeystore(password.password1);
console.log(data);